### ISSUE TITLE
Исходник требует pytorch quantization.

### ISSUE THREAD

**Issue by UDASHA777** [sawylka99/vehiclecountingcrossroad#1]
Здравствуйте, я ознакомился с вашими исходниками, попробовал запустить и столкнулся с проблемой, возникает ошибка not found cashe, и говорит pytorch quantization не найден. Я всячески его устанавливал, но сваливается в ошибку. Можете помочь советом? И работала ли она у вас? Я студент самоучка. Компьютерное зрение начал изучать.

**Comment by sawylka99** [comment]
Привет, я могу дать свои контакты и там попробовать тебе помочь
***@***.***
дискорд sawylka99#0425

  
>Вторник, 28 июня 2022, 14:02 +03:00 от UDASHA777 ***@***.***>:
> 
> 
>Здравствуйте, я ознакомился с вашими исходниками, попробовал запустить и столкнулся с проблемой, возникает ошибка not found cashe, и говорит pytorch quantization не найден. Я всячески его устанавливал, но сваливается в ошибку. Можете помочь советом? И работала ли она у вас? Я студент самоучка. Компьютерное зрение начал изучать.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <sawylka99/vehiclecountingcrossroad/issues/1 @ github . com> 
 
 
--
С уважением, магистрант ФПиКТ группы Р4122
Саша Попович

**Comment by sawylka99** [comment]
Попробуй так же руками ввести команда
pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html - gpu torch
pip3 install opencv-python - cv2

**Comment by UDASHA777** [comment]
> Попробуй так же руками ввести команду pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html - gpu факел pip3 установить opencv-python - pip cv2 установить pafy - pafy

Доброго дня. Спасибо, сообщение только сегодня увидел. Попробую сегодня попытаться еще сам запустить, если не получится, предлагаю завтра(29.06.2022) в 20:00 по Уфимскому времени созвониться. Я сам из Уфы.

**Comment by sawylka99** [comment]
У тебя как я понял сама моделька не скачана, по этому и не запускается,
pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html - gpu torch
вот это должно помочь.
Еще очень важно работать в одном виртуальном окружении.
У студентов которые дальше этим пользовались вроде проблем не возникало. 
Я в принципе почти всегда за компом, позвони в диск я увижу и отвечу!
